version: '2'
services:
    postgres:
        image: postgres
        ports:
          - '5433:5432'
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: symfony
          TZ: Europe/Paris
          PGTZ: Europe/Paris
        volumes:
          - db-data:/var/lib/postgresql/data
          - ./var:/var/www/var
    php:
        build: php-fpm
        ports:
          - '9002:9000'
        volumes:
          - ../:/var/www/symfony:cached
          - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
          - postgres
    nginx:
        build: nginx
        ports:
          - '8000:80'
        links:
          - php
        volumes_from:
          - php
        volumes:
          - ./logs/nginx/:/var/log/nginx:cached
volumes:
  db-data:
    driver: local
